language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
script:
  - npm test
before_script:
  - nvm install 13
  - nvm use 13
  - npm i -g npm@6
  - npm i
  - touch tests.db
  - chmod a+w tests.db
  - cd src/api/ && composer update && cd ../../
if: fork = false
after_success:
  - echo -e "<?php\n  print phpversion();" > version.php
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  - touch fakeconfig
  - echo "OAUTH_ACCESS_TOKEN=$OAUTH_ACCESS_TOKEN" > fakeconfig
  - ./dropbox_uploader.sh -f fakeconfig upload coverage/api coverage-$(php version.php)/
  - ./dropbox_uploader.sh -f fakeconfig upload coverage/app/lcov-report coverage-$(php version.php)/

